import type { ClothingItem, Collection } from '@/lib/types';

export const clothingItems: ClothingItem[] = [
  {
    id: 'mom-boho-dress',
    name: 'Ethereal Boho Maxi Dress',
    description: 'Flowy and free-spirited, this bohemian maxi dress is perfect for sunny afternoons and countryside picnics.',
    price: 89.99,
    familyMember: 'Mom',
    style: 'Bohemian',
    color: 'Cream',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 'dad-linen-shirt',
    name: 'Breezy Linen Button-Up',
    description: 'Stay cool and stylish in this classic linen shirt. A versatile piece for beach weddings or casual dinners.',
    price: 74.99,
    familyMember: 'Dad',
    style: 'Casual',
    color: 'Light Blue',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 'child-romper',
    name: 'Playful Gingham Romper',
    description: 'An adorable and comfortable one-piece for your little one, made from soft, breathable cotton.',
    price: 45.00,
    familyMember: 'Child',
    style: 'Casual',
    color: 'Yellow',
    sizes: ['1T', '2T', '3T', '4T'],
  },
  {
    id: 'mom-cable-knit',
    name: 'Cozy Cable-Knit Sweater',
    description: 'A timeless wardrobe staple. This cozy sweater is perfect for chilly evenings and autumn strolls.',
    price: 95.50,
    familyMember: 'Mom',
    style: 'Casual',
    color: 'Oatmeal',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 'dad-plaid-shirt',
    name: 'Rugged Plaid Flannel Shirt',
    description: 'A classic flannel that combines comfort and durability. Ideal for layering on a crisp autumn day.',
    price: 69.99,
    familyMember: 'Dad',
    style: 'Casual',
    color: 'Red and Black',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 'child-corduroy',
    name: 'Sturdy Corduroy Overalls',
    description: 'Ready for any adventure, these corduroy overalls are both cute and tough enough for playtime.',
    price: 52.00,
    familyMember: 'Child',
    style: 'Casual',
    color: 'Forest Green',
    sizes: ['1T', '2T', '3T', '4T'],
  },
  {
    id: 'mom-swimsuit',
    name: 'Elegant One-Piece Swimsuit',
    description: 'A flattering and chic swimsuit with a timeless design, perfect for a family day at the beach.',
    price: 110.00,
    familyMember: 'Mom',
    style: 'Sporty',
    color: 'Navy Blue',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 'dad-boardshorts',
    name: 'Quick-Dry Performance Boardshorts',
    description: 'Comfortable, flexible, and fast-drying boardshorts for active dads who love the water.',
    price: 65.00,
    familyMember: 'Dad',
    style: 'Sporty',
    color: 'Teal',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 'child-sun-hat',
    name: 'Reversible Bucket Sun Hat',
    description: 'Protect your little one from the sun with this fun and functional reversible hat.',
    price: 25.00,
    familyMember: 'Child',
    style: 'Casual',
    color: 'Multi-color',
    sizes: ['One Size'],
  },
  {
    id: 'mom-velvet-dress',
    name: 'Luxe Velvet Holiday Dress',
    description: 'A stunning velvet dress for special occasions. Rich in color and soft to the touch.',
    price: 150.00,
    familyMember: 'Mom',
    style: 'Formal',
    color: 'Burgundy',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 'dad-wool-coat',
    name: 'Classic Wool Topcoat',
    description: 'A sophisticated and warm topcoat that elevates any formal look during the colder months.',
    price: 250.00,
    familyMember: 'Dad',
    style: 'Formal',
    color: 'Charcoal',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 'child-tuxedo',
    name: 'Dapper Mini Tuxedo Set',
    description: 'An impossibly cute miniature tuxedo for the little gentleman in your family.',
    price: 120.00,
    familyMember: 'Child',
    style: 'Formal',
    color: 'Black',
    sizes: ['2T', '3T', '4T', '5'],
  },
];

export const collections: Collection[] = [
  {
    id: 'collection-autumn',
    name: 'Autumn Harvest',
    description: 'Embrace the crisp air and golden hues of fall with our cozy and coordinated Autumn Harvest collection.',
    image: { id: 'collection-autumn' },
    itemIds: ['mom-cable-knit', 'dad-plaid-shirt', 'child-corduroy'],
  },
  {
    id: 'collection-beach',
    name: 'Summer Seaside',
    description: 'Light, airy, and ready for sunshine. Our Summer Seaside collection is perfect for your family\'s beach adventures.',
    image: { id: 'collection-beach' },
    itemIds: ['mom-swimsuit', 'dad-boardshorts', 'child-sun-hat', 'dad-linen-shirt'],
  },
  {
    id: 'collection-holiday',
    name: 'Holiday Sparkle',
    description: 'Celebrate in style with our elegant and festive Holiday Sparkle collection, designed for memorable moments.',
    image: { id: 'collection-holiday' },
    itemIds: ['mom-velvet-dress', 'dad-wool-coat', 'child-tuxedo'],
  },
];
